version: '3.9'

services:
  skyvern:
    image: public.ecr.aws/skyvern/skyvern:latest
    restart: on-failure
    ports:
      - "8000:8000"        # Skyvern API
      - "9222:9222"        # For browser automation via CDP
    env_file:
      - .env
    volumes:
      - ./artifacts:/data/artifacts
      - ./videos:/data/videos
      - ./har:/data/har
      - ./log:/data/log
      - ./.streamlit:/app/.streamlit
      # Optional: mount local code for dev
      # - ./skyvern:/app/skyvern
      # - ./alembic:/app/alembic
    environment:
      - ENABLE_CODE_BLOCK=true
    networks:
      default:
        external: true
        name: skyvern-net

    healthcheck:
      test: ["CMD", "test", "-f", "/app/.streamlit/secrets.toml"]
      interval: 5s
      timeout: 5s
      retries: 5
