version: '3.9'

services:
  skyvern-ui:
    image: public.ecr.aws/skyvern/skyvern-ui:latest
    restart: on-failure
    ports:
      - 8081:8080           # UI
      - 9091:9090           # Artifact API
    volumes:
      - ./artifacts:/data/artifacts
      - ./videos:/data/videos
      - ./har:/data/har
      - /home/ubuntu/skyvern-ui-streamlit:/app/.streamlit
    env_file:
      - skyvern-frontend/.env
    environment:
      - VITE_ENABLE_CODE_BLOCK=true
